require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

def ccache_enabled?(podfile_properties)
  # Environment variable takes precedence
  return ENV['USE_CCACHE'] == '1' if ENV['USE_CCACHE']
  
  # Fall back to Podfile properties
  podfile_properties['apple.ccacheEnabled'] == 'true'
end

ENV['RCT_NEW_ARCH_ENABLED'] ||= '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] ||= podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
ENV['RCT_USE_RN_DEP'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'

prepare_react_native_project!

target 'Pushly' do
  use_frameworks! :linkage => :static

  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(\'expo/bin/autolinking\')',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => ccache_enabled?(podfile_properties),
    )

    # [expo-targets-resource-bundle-signing-start]
    # Fix Xcode 14+ code signing for resource bundles
    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) && target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
    # [expo-targets-resource-bundle-signing-end]

    # MediaPipeTasksVision/MediaPipeTasksCommon CocoaPods metadata can emit `-lMediaPipe...`
    # in this static-framework setup, which fails to resolve. Force framework-style linking.
    pods_pushly_xcconfigs = Dir.glob(File.join(__dir__, 'Pods', 'Target Support Files', 'Pods-Pushly', 'Pods-Pushly.*.xcconfig'))
    pods_pushly_xcconfigs.each do |xcconfig_path|
      next unless File.exist?(xcconfig_path)

      contents = File.read(xcconfig_path)
      contents = contents.gsub('-l"MediaPipeTasksCommon"', '-framework "MediaPipeTasksCommon"')
      contents = contents.gsub('-l"MediaPipeTasksVision"', '-framework "MediaPipeTasksVision"')

      contents = contents.gsub(/^(FRAMEWORK_SEARCH_PATHS = .*)$/) do |line|
        if line.include?('${PODS_XCFRAMEWORKS_BUILD_DIR}/MediaPipeTasksCommon')
          line
        else
          %(#{line} "${PODS_XCFRAMEWORKS_BUILD_DIR}/MediaPipeTasksCommon" "${PODS_XCFRAMEWORKS_BUILD_DIR}/MediaPipeTasksVision")
        end
      end

      File.write(xcconfig_path, contents)
    end
  end
end

target 'PushlyMonitorTarget' do
    use_frameworks! :linkage => :static
    platform :ios, '16.0'
  end
